[package]
name = "rhizome-reed-write-ts"
description = "TypeScript writer for reed IR"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-reed-ir.workspace = true
