[package]
name = "rhizome-reed-lua"
description = "Lua reader/writer for reed IR"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rhizome-reed-ir.workspace = true
thiserror.workspace = true
